[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "766774e8205a427b374d214b63c07f672cc865eb"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MPICH.download]]
    sha256 = "dd6bdd96edce6cea1f2c70fe4afa6f456eff4c79f0277fccb9025147eb58be50"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "54cc6aa34a96f5e0471aefafb212832b087d1c7b"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "996fc31e871fd32792d47d396ddc69752c29611646bd5dcf05dba5bcfc16e2cd"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "9147b2333be2a60052543d6a3a79249fad837cfd"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "309c3f63b6ad4d9a5f75ada9100a2250c09b7dc0af5d931a10e0b2e5a3db2643"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "aarch64"
git-tree-sha1 = "4f049a5227956df9e993003cb22a345bb96bf8e3"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[MPICH.download]]
    sha256 = "9d6c500479b202818161e64ca068d175be9a6dce036f719b35e35a328d7ef039"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c24b98ceb260853e4e383b85f93101e674dd33a5"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "a762bd3c7b64c2893f500c42ecf070f2dc5f91c6e3043823d633c0edc4af48ae"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35c9088571fccdecff099351a49f85f6e1bed849"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "c9a047be08b7688d917dc818dd70a2abe65014f9f217e2f246fc152d0c3459e2"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.armv6l-linux-musleabihf-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f3bfd84b2a7b2c1adfa5396d4e774978087d3ca0"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "e32276e1e5a572666072d13c43d585fa96d851790daf48d86bb70d4d8fc970cc"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48ecf8ea29d46d46f34467e6d661ed7b1fce7508"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "5bae51e5e30fd8fc5e3bb800fc45480484bc91a6f41cb8ecc0e41be203404a03"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.armv7l-linux-musleabihf-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "i686"
git-tree-sha1 = "d7402972fcb07223459439fe6e7cecc44a0e6c69"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "e255482ef6bc945abba72750ab3fc107234ac60aeef191df31e80d418099e017"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "i686"
git-tree-sha1 = "900b460417e5d5881d4dd4142ea20aa8b6c8a118"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "860a7e507576a402cb6b9c59919d510fe761f7d99a363521cc1349b6fc9cbb5a"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.i686-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "powerpc64le"
git-tree-sha1 = "64817ca720412bae5383c69060246ca56e67473d"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "135a995466aa7a6cbcd295c856741381c1b0916686cc917483649fc0c30ddcd1"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "riscv64"
git-tree-sha1 = "e368140d8343330a6d3aa1c0db3fdb2856bf2806"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "2eb6f4f00b86e9281e2b1d46bb9cab26fd73fb781f2f387e2f7dc0049b10a95c"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "451e3ad27ba8c39d4be1c522efcba5a46d97ace9"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MPICH.download]]
    sha256 = "473e599787e92c26450ba58df0fe248f97c674785e8d6d23f9dbf95c57484566"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "cadc2071f67bfef18dfa2b4b2f8fbd644ab58635"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "ce0409b89dd5d6a9d0ad28172a50e9115cf5ffa0b573b156b9a323b99d656d82"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "178fdf89f27e57af10f16893811c5f83398ab4c4"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "1176e9802f26ef727038c725710cc6fec17522b06b1129d9af65212fb8761e17"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "55c078e38f251281f6c6d5665b88f2faf069905d"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[MPICH.download]]
    sha256 = "c512185abd5a4c678b7cf51efce6de1b4c1f4fb1d4228aa4304f57747dcc7d0c"
    url = "https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v5.0.0+0/MPICH.v5.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
